<?php

use App\BasisPengetahuan;
use Illuminate\Database\Seeder;

class BasisPengetahuanTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('basispengetahuan')->delete();

        $bp = [
            [
                'kode' => 'B-1',
                'mb' => '0.75',
                'md' => '0.1',
                'id_gejala' => '1',
                'id_penyakit' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-2',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '2',
                'id_penyakit' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-3',
                'mb' => '0.7',
                'md' => '0.2',
                'id_gejala' => '3',
                'id_penyakit' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-4',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '4',
                'id_penyakit' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-5',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '5',
                'id_penyakit' => '1',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-6',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '6',
                'id_penyakit' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-7',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '7',
                'id_penyakit' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-8',
                'mb' => '0.7',
                'md' => '0.1',
                'id_gejala' => '8',
                'id_penyakit' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-9',
                'mb' => '0.65',
                'md' => '0.2',
                'id_gejala' => '9',
                'id_penyakit' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-10',
                'mb' => '0.7',
                'md' => '0.2',
                'id_gejala' => '10',
                'id_penyakit' => '2',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-11',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '11',
                'id_penyakit' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-12',
                'mb' => '0.85',
                'md' => '0.1',
                'id_gejala' => '12',
                'id_penyakit' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-13',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '13',
                'id_penyakit' => '3',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-14',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '13',
                'id_penyakit' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-15',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '14',
                'id_penyakit' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-16',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '15',
                'id_penyakit' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-17',
                'mb' => '0.7',
                'md' => '0.2',
                'id_gejala' => '16',
                'id_penyakit' => '4',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-18',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '1',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-19',
                'mb' => '0.7',
                'md' => '0.2',
                'id_gejala' => '13',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-20',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '17',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-21',
                'mb' => '0.7',
                'md' => '0.25',
                'id_gejala' => '18',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-22',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '19',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-23',
                'mb' => '0.65',
                'md' => '0.25',
                'id_gejala' => '20',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-24',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '21',
                'id_penyakit' => '5',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-25',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '20',
                'id_penyakit' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-26',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '22',
                'id_penyakit' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-27',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '23',
                'id_penyakit' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-28',
                'mb' => '0.7',
                'md' => '0.1',
                'id_gejala' => '24',
                'id_penyakit' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-29',
                'mb' => '0.6',
                'md' => '0.3',
                'id_gejala' => '25',
                'id_penyakit' => '6',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-30',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '13',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-31',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '16',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-32',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '17',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-33',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '18',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-34',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '26',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-35',
                'mb' => '0.75',
                'md' => '0.25',
                'id_gejala' => '27',
                'id_penyakit' => '7',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-36',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '18',
                'id_penyakit' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-37',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '22',
                'id_penyakit' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-38',
                'mb' => '0.8',
                'md' => '0.2',
                'id_gejala' => '28',
                'id_penyakit' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-39',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '29',
                'id_penyakit' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-40',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '30',
                'id_penyakit' => '8',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-41',
                'mb' => '0.7',
                'md' => '0.2',
                'id_gejala' => '13',
                'id_penyakit' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-42',
                'mb' => '0.75',
                'md' => '0.2',
                'id_gejala' => '17',
                'id_penyakit' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-43',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '21',
                'id_penyakit' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-44',
                'mb' => '0.6',
                'md' => '0.2',
                'id_gejala' => '31',
                'id_penyakit' => '9',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-45',
                'mb' => '0.6',
                'md' => '0.3',
                'id_gejala' => '13',
                'id_penyakit' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-46',
                'mb' => '0.75',
                'md' => '0.1',
                'id_gejala' => '14',
                'id_penyakit' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-47',
                'mb' => '0.8',
                'md' => '0.15',
                'id_gejala' => '15',
                'id_penyakit' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kode' => 'B-48',
                'mb' => '0.8',
                'md' => '0.1',
                'id_gejala' => '32',
                'id_penyakit' => '10',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        BasisPengetahuan::insert($bp);
    }
}
